"""temperature

Revision ID: d46bcb6f5042
Revises: 731bdaae1565
Create Date: 2024-08-29 08:14:02.614782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d46bcb6f5042"
down_revision: Union[str, None] = "731bdaae1565"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temprerature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_time", sa.DateTime(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "city", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "city",
        "additional_info",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=511),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "city",
        "additional_info",
        existing_type=sa.String(length=511),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "city", "name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_table("temprerature")
    # ### end Alembic commands ###
